# Forwarded port should be declared as :
# service-name:
#   internal_port: XXXX
#   external_port: YYYY
#   protocol: 'ZZZ'
#
# With XXXX the internal port, YYYY the external port and ZZZ the protocol (TCP or UDP)
# Additional fields can be set:
# description: "A description to help understand the port forwarding"


wireguard:
  description: "Wireguard port"
  internal_port: 51820
  external_port: 51820
  protocol: 'UDP'

transmission-tcp:
  description: "Transmission TCP peer port"
  internal_port: 51413
  external_port: 51413
  protocol: 'TCP'

transmission-udp:
  description: "Transmission UDP peer port"
  internal_port: 51413
  external_port: 51413
  protocol: 'UDP'
